[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'


[tool.isort]
profile = 'black'
line_length = 120
py_version = 310

[tool.mypy]
exclude = [
    'venv',
    '\.venv',
    '\.git',
    '__pycache__',
    'build',
    'dist',
    'tests',
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
